version: '3.9'

services:
  api:
    container_name: ${PROJECT_NAME:-base_repository}_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE:-dev}
      args:
        - PORT=${API_PORT:-4000}
    ports:
      - "${API_PORT:-4000}:${API_PORT:-4000}"
      - "9228:9228"
    labels:
      - traefik.enable=true
      - traefik.docker.network=external_network
      - traefik.http.routers.api.entrypoints=${ENTRYPOINT:-http}
      - traefik.http.routers.api.tls=${TLS:-false}
      - traefik.http.routers.api.tls.certresolver=lets-encrypt
      - traefik.http.routers.api.rule=Host(`${API_DOMAIN:-api.localhost}`)
      - traefik.http.services.api.loadbalancer.server.port=${API_PORT:-4000}
      - traefik.http.routers.api.middlewares=rateLimit,log4shell,gzipCompress,securityHeadersPolicy # TODO: VALIDAR EL MIDDLEWARE securityHeaders
    environment:
      - MINIO_EXPOSE_HOST=${S3_DOMAIN:-s3.localhost}
      - MINIO_EXPOSE_HTTPS=${TLS:-true}
      - PORT=${API_PORT:-4000}
      - MINIO_PRIVATE_BUCKET=${S3_PRIVATE_BUCKET:-private.baserepository}
      - MINIO_PUBLIC_BUCKET=${S3_PUBLIC_BUCKET:-public.baserepository}
      - MINIO_REGION=${S3_REGION:-us-east-1}
    volumes:
      - api:/app
    networks:
      - external_network

networks:
  external_network:
    external: true
    name:  external_${PROJECT_NAME:-base_repository}_network

volumes:
  api:
    driver: "local"
    name: ${PROJECT_NAME:-base_repository}_api
