version: '3.9'

services:

  proxy:
    container_name: ${PROJECT_NAME:-base_repository}_proxy
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.docker.network=external_network
      - traefik.http.routers.proxy.tls=${TLS:-false}
      - traefik.http.routers.proxy.tls.certresolver=lets-encrypt
      - traefik.http.routers.proxy.entrypoints=${ENTRYPOINT:-http}
      - traefik.http.routers.proxy.rule=Host(`${PROXY_DOMAIN:-proxy.localhost}`)
      - traefik.http.services.proxy.loadbalancer.server.port=8080
      # TODO: Cambiar el password
      - traefik.http.middlewares.auth.basicauth.users=${LOAD_USERS:-nodebaserepository:$$apr1$$RTZSd6uA$$9zpPRgArFsHX2UWgPNXL..}
      - traefik.http.middlewares.auth.basicauth.usersfile=/usersfile
      # Middleware Redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # Middleware RateLimit
      - traefik.http.middlewares.rateLimit.ratelimit.average=500
      - traefik.http.middlewares.rateLimit.ratelimit.burst=1000
      - traefik.http.middlewares.rateLimit.ratelimit.period=1m
      # Middleware SecurityHeaders
      - traefik.http.middlewares.securityHeaders.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.securityHeaders.headers.contentTypeNosniff=true
      - traefik.http.middlewares.securityHeaders.headers.referrerPolicy=same-origin
      - traefik.http.middlewares.securityHeaders.headers.accessControlMaxAge=31536000
      - traefik.http.middlewares.securityHeaders.headers.accessControlAllowHeaders=true
      - traefik.http.middlewares.securityHeaders.headers.accessControlExposeHeaders=true
      - traefik.http.middlewares.securityHeaders.headers.framedeny=true
      - traefik.http.middlewares.securityHeaders.headers.browserxssfilter=true
      - traefik.http.middlewares.securityHeaders.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT,DELETE"
      - traefik.http.middlewares.securityHeaders.headers.stsSeconds=31536000
      - traefik.http.middlewares.securityHeaders.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.securityHeaders.headers.forceSTSHeader=true
      - traefik.http.middlewares.securityHeaders.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.securityHeaders.headers.browserXssFilter=true
      - traefik.http.middlewares.securityHeaders.headers.customBrowserXssValue=1
      - traefik.http.middlewares.securityHeaders.headers.stsPreload=true
      # Middleware SecurityHeadersPolicy
      - traefik.http.middlewares.securityHeadersPolicy.headers.contentSecurityPolicy=default-src *; script-src * 'unsafe-inline'"
      # Middleware GzipCompress
      - traefik.http.middlewares.gzipCompress.compress=true
      # Middleware Log4Shell
      - traefik.http.middlewares.log4shell.plugin.plugin-log4shell.errorcode=200
      # Global Redirect to https
      - traefik.http.routers.redirs.entrypoints=http
      - ${APPLY_REDIRECT:+traefik.http.routers.redirs.middlewares=redirect-to-https}
      - ${APPLY_REDIRECT:+traefik.http.routers.redirs.rule=}hostregexp(`{host:.+}`)
      # Apply middlewares
      - traefik.http.routers.proxy.middlewares=auth,rateLimit,securityHeaders,log4shell
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../.traefik/letsencrypt:/letsencrypt
      - ./usersfile:/usersfile
    networks:
      - external_network
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.lets-encrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.lets-encrypt.acme.email=${ACME_EMAIL:-user@baserepository.com}"
      - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=http"
      - "--experimental.plugins.plugin-log4shell.modulename=github.com/traefik/plugin-log4shell"
      - "--experimental.plugins.plugin-log4shell.version=v0.1.2"
      - ${ACME_STAGING:+--certificatesresolvers.lets-encrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory}

networks:
  external_network:
    external: true
    name:  external_${PROJECT_NAME:-base_repository}_network
