version: '3.9'

services:

  doc:
    container_name: ${PROJECT_NAME:-base_repository}_api_doc
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: doc
    ports:
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.docker.network=external_network
      - traefik.http.routers.doc.entrypoints=${ENTRYPOINT:-http}
      - traefik.http.routers.doc.tls=${TLS:-false}
      - traefik.http.routers.doc.tls.certresolver=lets-encrypt
      - traefik.http.routers.doc.rule=Host(`${API_DOC_DOMAIN:-doc.api.localhost}`)
      - traefik.http.services.doc.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.users=${LOAD_USERS:-nodebaserepository:$$apr1$$RTZSd6uA$$9zpPRgArFsHX2UWgPNXL..}
      - traefik.http.middlewares.auth.basicauth.usersfile=/usersfile
      - traefik.http.routers.doc.middlewares=auth,rateLimit,log4shell,securityHeaders
    volumes:
      - ./usersfile:/usersfile
    networks:
      - external_network

networks:
  external_network:
    external: true
    name:  external_${PROJECT_NAME:-base_repository}_network
